dist: xenial

language: python

python:
  - 3.6
  - 3.7
  - nightly
matrix:
  allow_failures:
    - python: nightly
env:
  - REQUIREMENTS=dev-requirements/dev-requirements.txt
  - REQUIREMENTS=dev-requirements/dev-requirements-cython.txt
  - REQUIREMENTS=dev-requirements/dev-requirements-ciso.txt
  - REQUIREMENTS=dev-requirements/dev-requirements-cython-ciso.txt
install:
  - pip install -r $REQUIREMENTS --upgrade
  - pip install -e .
script:
  - make check_format
  - make test
after_success: codecov
sudo: required
services:
  - docker
before_install:
  - docker pull yandex/clickhouse-server
  - docker run -p 8123:8123 -d --name cs yandex/clickhouse-server
  - docker ps -a
