language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
env:
  - WITH_CYTHON=dev-requirements.txt
  - WITH_CYTHON=dev-requirements-cython.txt
install:
  - pip install -r $WITH_CYTHON
  - pip install -e .
script:
  - pytest tests.py --cov aiochclient
after_success: codecov
sudo: required
services:
  - docker
before_install:
  - docker pull yandex/clickhouse-server
  - docker run -p 8123:8123 -d --name cs yandex/clickhouse-server
  - docker ps -a
